### ISSUE TITLE
Processes are not terminated after integration tests

### ISSUE THREAD

**Issue by michaellihs** [bazaarvoice/maven-process-plugin#19]
We use your plugin on a Windows 7 machine and a Windows 8 machine. On Windows 7 it works perfectly and all processes that we start before the integration tests are terminated as expected. On Windows 8 though, the processes are not stopped and "live on".

To be more precisely, we start 3 Spring Boot Apps using `mvn spring-boot:run` in 3 separate directories.

Do you have any idea why we see this behavior and how we probably could fix it? 

Thanks a lot for any support,

Michael

**Comment by ldeck** [comment]
Not sure what might be happening here, but have you tried launching jars instead?

i.e., my first attempt last year was doing just what you've done but I found it didn't always work reliably on various windows systems. Additionally, it's likely not what you'd want on CI.

On CI I wanted, for example, to use the maven-dependency-plugin to copy (in the package phase, for example) the relevant `*.jar` files from our maven repo.

In that case, the arguments to the process-exec plugin needed to be of the form "java -cp ..." instead.

For development, then, when not in `prodmode`, you can use another profile which will use the maven-antrun-plugin, for example, to build the relevant jar (mvn package) and copy it into the target dir so that in your pre-integration-test phase, the jar could be launched (whether copied from a remote repo or locally).

**Comment by michaellihs** [comment]
hi @ldeck - thanks for your detailed answer! Yes - I tried launching jars indeed, before switching to `mvn`. The idea behind `mvn` was to assure that the latest code changes are used for testing the applications. We wanted to have the test to check whether everything works locally before committing to CI.

You are right, on CI, things look completely different - we would take compiled binaries there, run them in a integration environment... But locally we hoped to get a fast feedback whether things are still working.

Maybe the better solution would be to build each project before launching it as a jar. I will give it a try on Monday. First of all I will check, whether processes are cleanly terminated when using `java` instead of `mvn` on my colleague's machine.

Thanks again for your help!

**Comment by michaellihs** [comment]
hi @ldeck - as it turned out, it had nothing to do with Windows 7, but the Maven processes started with `mvn spring-boot:run` were not terminated after the integration tests. This happened with Windows 7 as well as with Windows 8. Starting the compiled jars with `java -jar ...` works perfectly on both platforms so we switched to this solution.

Thanks again for your help!

Michael
